name: effective_dart
version: 1.2.3
description: Linter rules corresponding to the guidelines in Effective Dart.
homepage: https://github.com/tenhobi/effective_dart
repository: https://github.com/tenhobi/effective_dart
issue_tracker: https://github.com/tenhobi/effective_dart/issues

environment:
  sdk: '>=2.0.0 <3.0.0'
